from __future__ import annotations

import json
from typing import Any

from fastapi import HTTPException, status

from app.modules.performance_intelligence.schemas import (
    ClassPerformanceIntelligenceResponse,
    SchoolPerformanceIntelligenceResponse,
    StudentPerformanceIntelligenceResponse,
)

from .schemas import PerformanceAIInsightResponse
from .service import ai_service


class PerformanceAIService:

    @staticmethod
    def _clean_payload(value: Any) -> Any:
        """
        Convert Pydantic/SQLAlchemy-derived objects into plain
        JSON-safe structures before sending them to AI.
        """
        if hasattr(value, "model_dump"):
            return PerformanceAIService._clean_payload(
                value.model_dump()
            )

        if isinstance(value, dict):
            return {
                str(key): PerformanceAIService._clean_payload(
                    item
                )
                for key, item in value.items()
            }

        if isinstance(value, (list, tuple)):
            return [
                PerformanceAIService._clean_payload(item)
                for item in value
            ]

        return value

    @staticmethod
    def _build_prompt(
        scope: str,
        data: Any,
    ) -> str:

        payload = PerformanceAIService._clean_payload(data)

        serialized = json.dumps(
            payload,
            ensure_ascii=False,
            separators=(",", ":"),
        )

        return f"""
You are the CoreOne Performance Intelligence AI Assistant.

Your task is to interpret VERIFIED performance and attendance
analytics generated by CoreOne.

Scope:
{scope}

The data below has already been calculated by CoreOne.
Do NOT invent, modify, estimate, or contradict any numerical
value contained in the data.

DATA:
{serialized}

Your responsibilities:
1. Explain the most important performance patterns.
2. Identify meaningful academic and attendance concerns.
3. Highlight strengths where appropriate.
4. Recommend practical educational interventions.
5. Keep recommendations appropriate for school administrators,
   teachers, and student support teams.
6. Never diagnose a medical, psychological, or behavioural
   condition.
7. Do not claim that attendance definitely caused academic
   performance changes. Describe relationships as patterns or
   possible contributing factors.
8. Do not expose internal database IDs unless they are useful
   for identifying a record internally.
9. Use clear professional educational language.
10. Do not use markdown headings or bullet symbols inside the
    returned strings.

Return ONLY valid JSON with exactly this structure:

{{
  "title": "Concise title",
  "summary": "Professional summary",
  "key_findings": [
    "Finding one",
    "Finding two",
    "Finding three"
  ],
  "recommendations": [
    "Recommendation one",
    "Recommendation two",
    "Recommendation three"
  ],
  "priority": "low"
}}

The priority must be exactly one of:
"low", "moderate", "high".

Do not include markdown.
"""

    @staticmethod
    def _mock_response(
        scope: str,
        data: Any,
    ) -> PerformanceAIInsightResponse:

        if scope == "student":
            summary = (
                "CoreOne identified the main academic and "
                "attendance patterns for this student. "
                "The findings should be reviewed alongside "
                "the student's wider academic context."
            )
            title = "Student Performance Insight"
        elif scope == "class":
            summary = (
                "CoreOne identified the main academic and "
                "attendance patterns for this class. "
                "The results can guide targeted classroom "
                "support and monitoring."
            )
            title = "Class Performance Insight"
        else:
            summary = (
                "CoreOne identified the main academic and "
                "attendance patterns across the school. "
                "The findings can support school-level "
                "planning and intervention."
            )
            title = "School Performance Insight"

        return PerformanceAIInsightResponse(
            scope=scope,
            title=title,
            summary=summary,
            key_findings=[
                "Review the academic averages and attendance indicators.",
                "Pay particular attention to the weakest performance areas.",
                "Monitor students or classes with repeated risk indicators.",
            ],
            recommendations=[
                "Prioritize targeted academic support where performance is lowest.",
                "Monitor attendance indicators for students requiring attention.",
                "Review progress again after the next available assessment period.",
            ],
            priority="moderate",
        )

    async def generate_insight(
        self,
        scope: str,
        data: Any,
    ) -> PerformanceAIInsightResponse:

        if scope not in {
            "student",
            "class",
            "school",
        }:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Invalid Performance AI scope.",
            )

        if getattr(data, "academic_result_count", None) == 0:
            # Student-specific safeguard. We still allow the AI
            # to explain the lack of published results.
            pass

        if (
            scope == "class"
            and isinstance(
                data,
                ClassPerformanceIntelligenceResponse,
            )
            and data.students_with_results == 0
        ):
            pass

        if (
            scope == "school"
            and isinstance(
                data,
                SchoolPerformanceIntelligenceResponse,
            )
            and data.students_with_results == 0
        ):
            pass

        if __import__(
            "app.core.config",
            fromlist=["settings"],
        ).settings.AI_MOCK_MODE:
            return self._mock_response(
                scope,
                data,
            )

        prompt = self._build_prompt(
            scope,
            data,
        )

        # Use the same AI client/configuration already used by
        # CoreOne's CBT AI service.
        client = ai_service._get_client()

        try:
            response = await client.responses.create(
                model=ai_service.model,
                input=prompt,
            )
        except Exception as exc:
            raise RuntimeError(
                "CoreOne Performance AI could not reach the AI service."
            ) from exc

        raw_text = response.output_text.strip()

        try:
            payload = json.loads(raw_text)
        except json.JSONDecodeError as exc:
            raise RuntimeError(
                "Performance AI returned an invalid insight format."
            ) from exc

        return PerformanceAIInsightResponse(
            scope=scope,
            title=str(
                payload.get(
                    "title",
                    "Performance Intelligence Insight",
                )
            ),
            summary=str(
                payload.get(
                    "summary",
                    "",
                )
            ),
            key_findings=[
                str(item)
                for item in payload.get(
                    "key_findings",
                    [],
                )
                if item is not None
            ],
            recommendations=[
                str(item)
                for item in payload.get(
                    "recommendations",
                    [],
                )
                if item is not None
            ],
            priority=(
                payload.get(
                    "priority",
                    "moderate",
                )
                if payload.get(
                    "priority",
                    "moderate",
                )
                in {
                    "low",
                    "moderate",
                    "high",
                }
                else "moderate"
            ),
        )


performance_ai_service = PerformanceAIService()
