"""add class teacher fields

Revision ID: 2778723874c8
Revises: e45186f44855
Create Date: 2026-07-20 00:57:56.401220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2778723874c8'
down_revision: Union[str, Sequence[str], None] = 'e45186f44855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classrooms', sa.Column('class_teacher_id', sa.Integer(), nullable=True))
    op.add_column('classrooms', sa.Column('class_teacher_assigned_by', sa.Integer(), nullable=True))
    op.add_column('classrooms', sa.Column('class_teacher_assigned_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_classrooms_class_teacher_id'), 'classrooms', ['class_teacher_id'], unique=False)
    op.create_foreign_key(
    'fk_classrooms_class_teacher_assigned_by',
    'classrooms',
    'users',
    ['class_teacher_assigned_by'],
    ['id'],
    ondelete='SET NULL',
)
    op.create_foreign_key(
    'fk_classrooms_class_teacher',
    'classrooms',
    'teachers',
    ['class_teacher_id'],
    ['id'],
    ondelete='SET NULL',
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
    'fk_classrooms_class_teacher_assigned_by',
    'classrooms',
    type_='foreignkey',
)
    op.drop_constraint(
    'fk_classrooms_class_teacher',
    'classrooms',
    type_='foreignkey',
)
    op.drop_index(op.f('ix_classrooms_class_teacher_id'), table_name='classrooms')
    op.drop_column('classrooms', 'class_teacher_assigned_at')
    op.drop_column('classrooms', 'class_teacher_assigned_by')
    op.drop_column('classrooms', 'class_teacher_id')
    # ### end Alembic commands ###
