"""add school branding

Revision ID: 3efc5ec96230
Revises: 8ce979d0a2cc
Create Date: 2026-07-12 22:44:42.960361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3efc5ec96230'
down_revision: Union[str, Sequence[str], None] = '8ce979d0a2cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_branding',
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('app_icon_url', sa.String(length=500), nullable=True),
    sa.Column('splash_image_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=20), nullable=False),
    sa.Column('secondary_color', sa.String(length=20), nullable=False),
    sa.Column('accent_color', sa.String(length=20), nullable=False),
    sa.Column('motto', sa.String(length=255), nullable=True),
    sa.Column('login_title', sa.String(length=255), nullable=True),
    sa.Column('login_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', name='uq_school_branding_school_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_school_branding_id'), 'school_branding', ['id'], unique=False)
    op.create_index(op.f('ix_school_branding_school_id'), 'school_branding', ['school_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_school_branding_school_id'), table_name='school_branding')
    op.drop_index(op.f('ix_school_branding_id'), table_name='school_branding')
    op.drop_table('school_branding')
    # ### end Alembic commands ###
