"""create youtube learning table

Revision ID: 42e8cf78b1b1
Revises: 3deb2a4e9f76
Create Date: 2026-07-11 06:33:28.561385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42e8cf78b1b1'
down_revision: Union[str, Sequence[str], None] = '3deb2a4e9f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
