"""expand ebook model

Revision ID: 6d173c5bbf22
Revises: d23c5791bb81
Create Date: 2026-08-07
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "6d173c5bbf22"
down_revision: Union[str, Sequence[str], None] = "d23c5791bb81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # The existing migration history does not guarantee that the
    # ebooks table exists at this revision. Create it if necessary.

    op.execute("""
        CREATE TABLE IF NOT EXISTS ebooks (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title VARCHAR(200) NOT NULL,
            author VARCHAR(150),
            description TEXT,
            file_url VARCHAR(500) NOT NULL,
            category VARCHAR(100),
            uploaded_by INTEGER NOT NULL,
            school_id INTEGER NOT NULL,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            uuid VARCHAR(36),
            created_at TIMESTAMP,
            updated_at TIMESTAMP,

            subject_id INTEGER,
            classroom_id INTEGER,
            cover_image_url VARCHAR(500),
            file_name VARCHAR(255),
            file_size INTEGER,
            file_type VARCHAR(100),
            featured BOOLEAN NOT NULL DEFAULT FALSE,
            download_count INTEGER NOT NULL DEFAULT 0,
            view_count INTEGER NOT NULL DEFAULT 0
        )
    """)

    # Existing databases may already have some of these columns.
    # Add only the missing ones.

    op.execute("""
        ALTER TABLE ebooks
        ADD COLUMN IF NOT EXISTS subject_id INTEGER
    """)

    op.execute("""
        ALTER TABLE ebooks
        ADD COLUMN IF NOT EXISTS classroom_id INTEGER
    """)

    op.execute("""
        ALTER TABLE ebooks
        ADD COLUMN IF NOT EXISTS cover_image_url VARCHAR(500)
    """)

    op.execute("""
        ALTER TABLE ebooks
        ADD COLUMN IF NOT EXISTS file_name VARCHAR(255)
    """)

    op.execute("""
        ALTER TABLE ebooks
        ADD COLUMN IF NOT EXISTS file_size INTEGER
    """)

    op.execute("""
        ALTER TABLE ebooks
        ADD COLUMN IF NOT EXISTS file_type VARCHAR(100)
    """)

    op.execute("""
        ALTER TABLE ebooks
        ADD COLUMN IF NOT EXISTS featured BOOLEAN NOT NULL DEFAULT FALSE
    """)

    op.execute("""
        ALTER TABLE ebooks
        ADD COLUMN IF NOT EXISTS download_count INTEGER NOT NULL DEFAULT 0
    """)

    op.execute("""
        ALTER TABLE ebooks
        ADD COLUMN IF NOT EXISTS view_count INTEGER NOT NULL DEFAULT 0
    """)

    # Make sure indexes exist.

    op.execute("""
        CREATE INDEX IF NOT EXISTS ix_ebooks_subject_id
        ON ebooks (subject_id)
    """)

    op.execute("""
        CREATE INDEX IF NOT EXISTS ix_ebooks_classroom_id
        ON ebooks (classroom_id)
    """)


def downgrade() -> None:
    op.execute("""
        DROP INDEX IF EXISTS ix_ebooks_classroom_id
    """)

    op.execute("""
        DROP INDEX IF EXISTS ix_ebooks_subject_id
    """)

    op.execute("""
        ALTER TABLE ebooks
        DROP COLUMN IF EXISTS view_count
    """)

    op.execute("""
        ALTER TABLE ebooks
        DROP COLUMN IF EXISTS download_count
    """)

    op.execute("""
        ALTER TABLE ebooks
        DROP COLUMN IF EXISTS featured
    """)

    op.execute("""
        ALTER TABLE ebooks
        DROP COLUMN IF EXISTS file_type
    """)

    op.execute("""
        ALTER TABLE ebooks
        DROP COLUMN IF EXISTS file_size
    """)

    op.execute("""
        ALTER TABLE ebooks
        DROP COLUMN IF EXISTS file_name
    """)

    op.execute("""
        ALTER TABLE ebooks
        DROP COLUMN IF EXISTS cover_image_url
    """)

    op.execute("""
        ALTER TABLE ebooks
        DROP COLUMN IF EXISTS classroom_id
    """)

    op.execute("""
        ALTER TABLE ebooks
        DROP COLUMN IF EXISTS subject_id
    """)
