"""add school_id to teachers

Revision ID: 980476b621d3
Revises: ffec24b36c29
Create Date: 2026-07-20 06:31:28.183896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '980476b621d3'
down_revision: Union[str, Sequence[str], None] = 'ffec24b36c29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('school_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_teachers_school_id'), 'teachers', ['school_id'], unique=False)
    op.create_foreign_key(None, 'teachers', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.drop_index(op.f('ix_teachers_school_id'), table_name='teachers')
    op.drop_column('teachers', 'school_id')
    # ### end Alembic commands ###
