"""add classroom to students

Revision ID: ab04ea5faae7
Revises: e40dea42c160
Create Date: 2026-07-11 17:14:51.348595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab04ea5faae7'
down_revision: Union[str, Sequence[str], None] = 'e40dea42c160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('classroom_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_students_classroom_id'), 'students', ['classroom_id'], unique=False)
    op.create_foreign_key(None, 'students', 'classrooms', ['classroom_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_index(op.f('ix_students_classroom_id'), table_name='students')
    op.drop_column('students', 'classroom_id')
    # ### end Alembic commands ###
