"""create teacher subject assignments

Revision ID: ffec24b36c29
Revises: 2778723874c8
Create Date: 2026-07-20 01:07:35.747975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffec24b36c29'
down_revision: Union[str, Sequence[str], None] = '2778723874c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_subjects',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('academic_session_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['academic_session_id'], ['academic_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'teacher_id', 'classroom_id', 'subject_id', 'academic_session_id', name='uq_teacher_subject_assignment'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_teacher_subjects_academic_session_id'), 'teacher_subjects', ['academic_session_id'], unique=False)
    op.create_index(op.f('ix_teacher_subjects_classroom_id'), 'teacher_subjects', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_teacher_subjects_id'), 'teacher_subjects', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_subjects_school_id'), 'teacher_subjects', ['school_id'], unique=False)
    op.create_index(op.f('ix_teacher_subjects_subject_id'), 'teacher_subjects', ['subject_id'], unique=False)
    op.create_index(op.f('ix_teacher_subjects_teacher_id'), 'teacher_subjects', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_subjects_teacher_id'), table_name='teacher_subjects')
    op.drop_index(op.f('ix_teacher_subjects_subject_id'), table_name='teacher_subjects')
    op.drop_index(op.f('ix_teacher_subjects_school_id'), table_name='teacher_subjects')
    op.drop_index(op.f('ix_teacher_subjects_id'), table_name='teacher_subjects')
    op.drop_index(op.f('ix_teacher_subjects_classroom_id'), table_name='teacher_subjects')
    op.drop_index(op.f('ix_teacher_subjects_academic_session_id'), table_name='teacher_subjects')
    op.drop_table('teacher_subjects')
    # ### end Alembic commands ###
